### ISSUE TITLE
Error on liquidation

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/Sovryn-Node#101]
trying to liquidate loan 0x59dfe102aa99cedc123fb0733dd5f79b8427b7bee6ce78bb02e14b4941395648 from wallet 0x83212bff8469874500b796d52784b8ff32cc9f6d, amount: 1.7162427995589315e+21
4|Sovryn node mainnet  | 2021-05-13T08:43:47: Sending val: 0
4|Sovryn node mainnet  | 2021-05-13T08:43:47: Nonce: 1484
4|Sovryn node mainnet  | 2021-05-13T08:43:47: Error: invalid BigNumber string (argument="value", value="1.7162427995589315e+21", code=INVALID_ARGUMENT, version=bignumber/5.1.0)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Logger.makeError (/home/ubuntu/Sovryn-Node/node_modules/@ethersproject/logger/lib/index.js:180:21)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Logger.throwError (/home/ubuntu/Sovryn-Node/node_modules/@ethersproject/logger/lib/index.js:189:20)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Logger.throwArgumentError (/home/ubuntu/Sovryn-Node/node_modules/@ethersproject/logger/lib/index.js:192:21)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Function.BigNumber.from (/home/ubuntu/Sovryn-Node/node_modules/@ethersproject/bignumber/lib/bignumber.js:201:27)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at NumberCoder.encode (/home/ubuntu/Sovryn-Node/node_modules/@ethersproject/abi/lib/coders/number.js:30:39)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at /home/ubuntu/Sovryn-Node/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Array.forEach (<anonymous>)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Object.pack (/home/ubuntu/Sovryn-Node/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at TupleCoder.encode (/home/ubuntu/Sovryn-Node/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at AbiCoder.encode (/home/ubuntu/Sovryn-Node/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at ABICoder.encodeParameters (/home/ubuntu/Sovryn-Node/node_modules/web3-eth-contract/node_modules/web3-eth-abi/lib/index.js:121:27)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at /home/ubuntu/Sovryn-Node/node_modules/web3-eth-contract/lib/index.js:439:20
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Array.map (<anonymous>)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Object._encodeMethodABI (/home/ubuntu/Sovryn-Node/node_modules/web3-eth-contract/lib/index.js:438:8)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Object._processExecuteArguments (/home/ubuntu/Sovryn-Node/node_modules/web3-eth-contract/lib/index.js:701:39)
4|Sovryn node mainnet  | 2021-05-13T08:43:47:     at Object._executeMethod (/home/ubuntu/Sovryn-Node/node_modules/web3-eth-contract/lib/index.js:720:68) {
4|Sovryn node mainnet  | 2021-05-13T08:43:47:   reason: 'invalid BigNumber string',
4|Sovryn node mainnet  | 2021-05-13T08:43:47:   code: 'INVALID_ARGUMENT',
4|Sovryn node mainnet  | 2021-05-13T08:43:47:   argument: 'value',
4|Sovryn node mainnet  | 2021-05-13T08:43:47:   value: '1.7162427995589315e+21'
4|Sovryn node mainnet  | 2021-05-13T08:43:47: }

**Comment by koirikivi** [comment]
Should be fixed as of #102
