### ISSUE TITLE
Bugfixes in stats

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Node#2]
There are lot of idle "Balances of"

![image](https://user-images.githubusercontent.com/40721795/107415668-e7a78c00-6b13-11eb-970e-ff6e3163e097.png)

Also the "Hi!" looks a bit odd

![image](https://user-images.githubusercontent.com/40721795/107415963-381ee980-6b14-11eb-9ec4-1ca99e21d78d.png)

Feel free to add any other bugs @jamiemadrox779

**Comment by jamiemadrox779** [comment]
Yes, frontend need a complete rewrite, as already mentioned

**Comment by Bitcoinera** [comment]
> Yes, frontend need a complete rewrite, as already mentioned

I'm thinking moving it to React. Probably the very best

**Comment by jamiemadrox779** [comment]
Do it, if you don't see too much overhead

**Comment by Bitcoinera** [comment]
> Do it, if you don't see too much overhead

I think I should do it in React in any case. I talked to @creed-victor and all the Sovryn apps are going to be made with React, so it is the best. For reusing components and styles, makes more sense

**Comment by Bitcoinera** [comment]
Although there is a good template using Vue.js already there used in [Sovryn-Node-Monitor](https://github.com/DistributedCollective/Sovryn-Node-Monitor) :sweat_smile: Maybe this is wiser to do

**Comment by jamiemadrox779** [comment]
Already solved
