### ISSUE TITLE
{"data":null}

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Node#37]
Sometimes I see this popping out among the Telegram notifications. I also see sometimes the error JSON RPC response `null` :thinking:  Needs to be investigated

**Comment by jamiemadrox779** [comment]
Coming from errors in arbitrage, swap function
await common.telegramBot.sendMessage(err);

**Comment by Bitcoinera** [comment]
Looking at the code I really don't see where this is coming from. I see it is always sending a message (when searching for all the "sendMessage" appearances). Maybe it was already fixed?
