### ISSUE TITLE
Rollover not working?

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Node#47]
After nearly two months using the Sovryn Node, I still don't have any rollover transactions recorded in the DB, which leads me to think something must be wrong with the logic and it is not working

**Comment by Bitcoinera** [comment]
Was testing this, but the testnet seems to be halted now?

![image](https://user-images.githubusercontent.com/40721795/113572163-03ad4280-9618-11eb-8eba-2b21b1ee608b.png)

**Comment by jamiemadrox779** [comment]
- Testnet is working fine (nodes + contracts). Please provide error messages.
- Rollover is also working fine, but there the event-log can't be written to the db because there is none, see comment 
"Rollover currently does not emit logs". So the db-log need to be rewritten or the log added to the contracts

**Comment by Bitcoinera** [comment]
> * Testnet is working fine (nodes + contracts). Please provide error messages.
> * Rollover is also working fine, but there the event-log can't be written to the db because there is none, see comment
>   "Rollover currently does not emit logs". So the db-log need to be rewritten or the log added to the contracts

Oh, I see. Maybe it is easier to rewrite the db-log?

**Comment by Bitcoinera** [comment]
I was also getting lots of transactions reverted yesterday. I need to check why was that actually. Do you [think](https://stackoverflow.com/questions/66144175/is-there-a-way-to-debug-transactions-in-rsk-network-which-could-be-the-best-way) this can help debug a transaction reverted by EVM?

**Comment by jamiemadrox779** [comment]
> > * Testnet is working fine (nodes + contracts). Please provide error messages.
> > * Rollover is also working fine, but there the event-log can't be written to the db because there is none, see comment
> >   "Rollover currently does not emit logs". So the db-log need to be rewritten or the log added to the contracts
> 
> Oh, I see. Maybe it is easier to rewrite the db-log?

yes

**Comment by jamiemadrox779** [comment]
> I was also getting lots of transactions reverted yesterday. I need to check why was that actually. Do you [think](https://stackoverflow.com/questions/66144175/is-there-a-way-to-debug-transactions-in-rsk-network-which-could-be-the-best-way) this can help debug a transaction reverted by EVM?

High likely due to not enough liquidity. I suggest to ignore it for now.
