### ISSUE TITLE
Arbitrage param error

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/Sovryn-Node#54]
103|Sovryn watcher-node  | 2021-04-07T19:15:45: Error on arbitrage tx 
103|Sovryn watcher-node  | 2021-04-07T19:15:45: Error: Please pass numbers as strings or BN objects to avoid precision errors.
103|Sovryn watcher-node  | 2021-04-07T19:15:45:     at Object.fromWei (/home/ubuntu/Sovryn-Node/node_modules/web3/node_modules/web3-utils/lib/index.js:220:15)

**Comment by koirikivi** [comment]
Should be fixed now.
