### ISSUE TITLE
Make the telegram notifications nicer and shorter

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/Sovryn-Node#61]
I suggest to use shortcuts, maybe something like this:

R: [link to tx on the Rsk-explorer]  
L: [link to tx on the Rsk-explorer] 
A: [link to tx on the Rsk-explorer] 

color green in case it was successful and red in case it wasn't

Do not send the whole error to telegram, such as
Error: Transaction has been reverted by the EVM:
....

**Comment by Bitcoinera** [comment]
It was impossible to use color for the letters. I spent quite some time looking for options, but the `<span>` tags and so on from HTML are not available and markdown has no colors, so it is not possible to do. All the rest is in
