### ISSUE TITLE
Bug balance retrieval on arbitrage

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/Sovryn-Node#65]
25|Sovryn node mainnet  | 2021-04-09T01:20:30: started checking prices (dynamic)
25|Sovryn node mainnet  | 2021-04-09T01:20:30: checking token usdt
25|Sovryn node mainnet  | 2021-04-09T01:20:30: rbtc amm balances: 95.164694566592473548 94.73419808074115081 0.430496485851322738
25|Sovryn node mainnet  | 2021-04-09T01:20:30: usdt amm balances: 1827506.850217078972746198 1828211.905121894766212677 -705.054904815793466479
25|Sovryn node mainnet  | 2021-04-09T01:20:30: Found arbitrage opportunity: 0.430496485851322738 rbtc -> usdt
25|Sovryn node mainnet  | 2021-04-09T01:20:30: prices: amm:  25017.90315  pricefeed:  25054.89548
25|Sovryn node mainnet  | 2021-04-09T01:20:30: arbitrage% 0.14786
25|Sovryn node mainnet  | 2021-04-09T01:20:30: arbitrage too low for threshold 0.2
25|Sovryn node mainnet  | 2021-04-09T01:20:30: checking token doc
25|Sovryn node mainnet  | 2021-04-09T01:20:30: rbtc amm balances: 0.90332425760261028 0.876990597775152399 0.026333659827457881
25|Sovryn node mainnet  | 2021-04-09T01:20:30: doc amm balances: 8722.941367366297636672 9426.936505281185488485 -703.995137914887851813
25|Sovryn node mainnet  | 2021-04-09T01:20:30: Found arbitrage opportunity: 0.026333659827457881 rbtc -> doc
25|Sovryn node mainnet  | 2021-04-09T01:20:30: prices: amm:  1528.65072  pricefeed:  1532.61900
25|Sovryn node mainnet  | 2021-04-09T01:20:30: arbitrage% 0.25959
25|Sovryn node mainnet  | 2021-04-09T01:20:30: EXECUTING ARBITRAGE! SELL rbtc, BUY doc!
25|Sovryn node mainnet  | 2021-04-09T01:20:30: no balance held in wallet -- cannot do anything

**Comment by koirikivi** [comment]
Yeah, this is because it checks `WRBTC` balance, not `RBTC` (even though we have the RBTC Wrapper Proxy). Need to fix. Thanks!
