### ISSUE TITLE
Finish all open TODOs in comments

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Node#7]

**Comment by jamiemadrox779** [comment]
bigbumber.js is not yet installed, why install aditional modules if web3 has all we need?

**Comment by Bitcoinera** [comment]
> bigbumber.js is not yet installed, why install aditional modules if web3 has all we need?

:thinking:  I got it installed in my `node_modules`. Maybe some of our current modules is dependent on `bignumber.js` ?

**Comment by jamiemadrox779** [comment]
not relevant anymore
